export const options = {
  regions: [
    'WOJ. DOLNOŚLĄSKIE',
    'WOJ. KUJAWSKO-POMORSKIE',
    'WOJ. LUBELSKIE',
    'WOJ. LUBUSKIE',
    'WOJ. ŁÓDZKIE',
    'WOJ. MAŁOPOLSKIE',
    'WOJ. MAZOWIECKIE',
    'WOJ. OPOLSKIE',
    'WOJ. PODKARPACKIE',
    'WOJ. PODLASKIE',
    'WOJ. POMORSKIE',
    'WOJ. ŚLĄSKIE',
    'WOJ. ŚWIĘTOKRZYSKIE',
    'WOJ. WARMIŃSKO-MAZURSKIE',
    'WOJ. WIELKOPOLSKIE',
    'WOJ. ZACHODNIOPOMORSKIE',
  ],
  cities: [
    'Bolesławiec',
    'Bielawa',
    'Dzierżoniów',
    'Głogów',
    'Góra',
    'Jawor',
    'Bolków',
    'Karpacz',
    'Kowary',
    'Piechowice',
    'Szklarska Poręba',
    'Kamienna Góra',
    'Duszniki-Zdrój',
    'Kłodzko',
    'Nowa Ruda',
    'Bystrzyca Kłodzka',
    'Stronie Śląskie',
    'Chojnów',
    'Lubań',
    'Lubin',
    'Gryfów Śląski',
    'Lwówek Śląski',
    'Mirsk',
    'Milicz',
    'Oleśnica',
    'Syców',
    'Twardogóra',
    'Oława',
    'Jelcz-Laskowice',
    'Polkowice',
    'Strzelin',
    'Środa Śląska',
    'Świdnica',
    'Świebodzice',
    'Strzegom',
    'Oborniki Śląskie',
    'Trzebnica',
    'Brzeg Dolny',
    'Wołów',
    'Długołęka',
    'Wierzbice',
    'Sobótka',
    'Ząbkowice Śląskie',
    'Ziębice',
    'Henryków',
    'Zgorzelec',
    'Bogatynia',
    'Złotoryja',
    'Jelenia Góra',
    'Legnica',
    'Wrocław',
    'Wałbrzych',
    'Aleksandrów Kujawski',
    'Ciechocinek',
    'Nieszawa',
    'Brodnica',
    'Górzno',
    'Wudzynek',
    'Koronowo',
    'Brzoza',
    'Solec Kujawski',
    'Chełmno',
    'Golub-Dobrzyń',
    'Kowalewo Pomorskie',
    'Łasin',
    'Inowrocław',
    'Gniewkowo',
    'Janikowo',
    'Kruszwica',
    'Lipno',
    'Skępe',
    'Jeziora Wielkie',
    'Mogilno',
    'Strzelno',
    'Nakło nad Notecią',
    'Szubin',
    'Radziejów',
    'Biskupice',
    'Rypin',
    'Sępólno Krajeńskie',
    'Więcbork',
    'Nowe',
    'Świecie',
    'Chełmża',
    'Czernikowo',
    'Gronowo',
    'Tuchola',
    'Wąbrzeźno',
    'Kowal',
    'Choceń',
    'Chodecz',
    'Izbica Kujawska',
    'Lubraniec',
    'Barcin',
    'Piechcin',
    'Gąsawa',
    'Janowiec Wielkopolski',
    'Łabiszyn',
    'Żnin',
    'Bydgoszcz',
    'Grudziądz',
    'Toruń',
    'Włocławek',
    'Międzyrzec Podlaski',
    'Małaszewicze',
    'Wisznice',
    'Biłgoraj',
    'Turobin',
    'Dubienka',
    'Siedliszcze',
    'Hrubieszów',
    'Horodło',
    'Janów Lubelski',
    'Modliborzyce',
    'Krasnystaw',
    'Zaburze',
    'Kraśnik',
    'Urzędów',
    'Lubartów',
    'Kock',
    'Ostrów Lubelski',
    'Bełżyce',
    'Bychawa',
    'Niedrzwica Duża',
    'Pszczela Wola',
    'Wysokie',
    'Milejów',
    'Kijany',
    'Łuków',
    'Zagoździe',
    'Józefów nad Wisłą',
    'Opole Lubelskie',
    'Kluczkowice-Osiedle',
    'Poniatowa',
    'Parczew',
    'Puławy',
    'Kazimierz Dolny',
    'Klementowice',
    'Nałęczów',
    'Radzyń Podlaski',
    'Wola Osowińska',
    'Komarówka Podlaska',
    'Ulan-Majorat',
    'Dęblin',
    'Ryki',
    'Sobieszyn',
    'Świdnik',
    'Piaski',
    'Tomaszów Lubelski',
    'Łaszczów',
    'Tyszowce',
    'Włodawa',
    'Grabowiec',
    'Krasnobród',
    'Szczebrzeszyn',
    'Zwierzyniec',
    'Biała Podlaska',
    'Chełm',
    'Lublin',
    'Zamość',
    'Kostrzyn nad Odrą',
    'Witnica',
    'Gubin',
    'Krosno Odrzańskie',
    'Międzyrzecz',
    'Skwierzyna',
    'Trzciel',
    'Nowa Sól',
    'Kożuchów',
    'Siedlisko',
    'Słubice',
    'Dobiegniew',
    'Drezdenko',
    'Strzelce Krajeńskie',
    'Sulęcin',
    'Świebodzin',
    'Zbąszynek',
    'Czerwieńsk',
    'Sulechów',
    'Zabór',
    'Żagań',
    'Iłowa',
    'Szprotawa',
    'Żary',
    'Lubsko',
    'Sława',
    'Wschowa',
    'Gorzów Wielkopolski',
    'Zielona Góra',
    'Bełchatów',
    'Kleszczów',
    'Szczerców',
    'Zelów',
    'Kutno',
    'Krośniewice',
    'Żychlin',
    'Łask',
    'Ostrów',
    'Łęczyca',
    'Łowicz',
    'Wiśniowa Góra',
    'Koluszki',
    'Tuszyn',
    'Drzewica',
    'Opoczno',
    'Mroczków Gościnny',
    'Żarnów',
    'Pabianice',
    'Działoszyn',
    'Pajęczno',
    'Gorzkowice',
    'Rozprza',
    'Sulejów',
    'Bujny',
    'Poddębice',
    'Radomsko',
    'Przedbórz',
    'Rawa Mazowiecka',
    'Biała Rawska',
    'Sieradz',
    'Warta',
    'Bolimów',
    'Godzianów',
    'Tomaszów Mazowiecki',
    'Spała',
    'Wieluń',
    'Wieruszów',
    'Zduńska Wola',
    'Wojsławice',
    'Głowno',
    'Ozorków',
    'Zgierz',
    'Aleksandrów Łódzki',
    'Bratoszewice',
    'Brzeziny',
    'Łódź',
    'Piotrków Trybunalski',
    'Skierniewice',
    'Bochnia',
    'Brzesko',
    'Czchów',
    'Szczurowa',
    'Chrzanów',
    'Libiąż',
    'Trzebinia',
    'Dąbrowa Tarnowska',
    'Szczucin',
    'Gorlice',
    'Biecz',
    'Bobowa',
    'Czernichów',
    'Krzeszowice',
    'Piekary',
    'Skała',
    'Skawina',
    'Radziszów',
    'Słomniki',
    'Świątniki Górne',
    'Giebułtów',
    'Zabierzów',
    'Limanowa',
    'Mszana Dolna',
    'Szczyrzyc',
    'Książ Wielki',
    'Miechów',
    'Dobczyce',
    'Myślenice',
    'Sułkowice',
    'Grybów',
    'Łącko',
    'Muszyna',
    'Nawojowa',
    'Stary Sącz',
    'Nowy Targ',
    'Szczawnica',
    'Czarny Dunajec',
    'Jabłonka',
    'Krościenko nad Dunajcem',
    'Niedzica',
    'Rabka-Zdrój',
    'Olkusz',
    'Wolbrom',
    'Oświęcim',
    'Kęty',
    'Zator',
    'Piotrkowice Małe',
    'Proszowice',
    'Jordanów',
    'Sucha Beskidzka',
    'Maków Podhalański',
    'Ciężkowice',
    'Gromnik',
    'Ryglice',
    'Tuchów',
    'Wojnicz',
    'Zakliczyn',
    'Zakopane',
    'Andrychów',
    'Kalwaria Zebrzydowska',
    'Wadowice',
    'Niepołomice',
    'Wieliczka',
    'Kraków',
    'Nowy Sącz',
    'Tarnów',
    'Białobrzegi',
    'Ciechanów',
    'Glinojeck',
    'Garwolin',
    'Łaskarzew',
    'Sobolew',
    'Żelechów',
    'Gostynin',
    'Milanówek',
    'Podkowa Leśna',
    'Grodzisk Mazowiecki',
    'Grójec',
    'Jasieniec',
    'Mogielnica',
    'Garbatka-Letnisko',
    'Kozienice',
    'Magnuszew',
    'Legionowo',
    'Rajszew',
    'Serock',
    'Komornica',
    'Sienno',
    'Solec nad Wisłą',
    'Łosice',
    'Maków Mazowiecki',
    'Krasnosielc',
    'Różan',
    'Mińsk Mazowiecki',
    'Mrozy',
    'Siennica',
    'Sulejówek',
    'Mława',
    'Radzanów',
    'Nowy Dwór Mazowiecki',
    'Nasielsk',
    'Budy Siennickie',
    'Pomiechówek',
    'Baranowo',
    'Czerwin',
    'Goworowo',
    'Kadzidło',
    'Łyse',
    'Myszyniec',
    'Troszyn',
    'Ostrów Mazowiecka',
    'Małkinia Górna',
    'Józefów',
    'Otwock',
    'Wiązowna',
    'Góra Kalwaria',
    'Konstancin-Jeziorna',
    'Łazy',
    'Piaseczno',
    'Tarczyn',
    'Drobin',
    'Gąbin',
    'Wyszogród',
    'Płońsk',
    'Raciąż',
    'Czerwińsk nad Wisłą',
    'Nowe Miasto',
    'Piastów',
    'Pruszków',
    'Brwinów',
    'Komorów',
    'Nadarzyn',
    'Przasnysz',
    'Chorzele',
    'Lipiny',
    'Przysucha',
    'Smogorzów',
    'Pułtusk',
    'Pionki',
    'Iłża',
    'Sierpc',
    'Sochaczew',
    'Szymanów',
    'Sokołów Podlaski',
    'Szydłowiec',
    'Błonie',
    'Laski',
    'Łomianki',
    'Ożarów Mazowiecki',
    'Węgrów',
    'Łochów',
    'Sadowne',
    'Stoczek',
    'Marki',
    'Zielonka',
    'Urle',
    'Radzymin',
    'Tłuszcz',
    'Wołomin',
    'Wyszków',
    'Zwoleń',
    'Bieżuń',
    'Żuromin',
    'Żyrardów',
    'Mszczonów',
    'Puszcza Mariańska',
    'Wiskitki',
    'Ostrołęka',
    'Płock',
    'Radom',
    'Siedlce',
    'Warszawa',
    'Brzeg',
    'Grodków',
    'Głubczyce',
    'Kietrz',
    'Kędzierzyn-Koźle',
    'Kluczbork',
    'Wołczyn',
    'Gogolin',
    'Krapkowice',
    'Zdzieszowice',
    'Namysłów',
    'Głuchołazy',
    'Łambinowice',
    'Nysa',
    'Otmuchów',
    'Paczków',
    'Dobrodzień',
    'Gorzów Śląski',
    'Olesno',
    'Praszka',
    'Dobrzeń Mały',
    'Dobrzeń Wielki',
    'Niemodlin',
    'Prószków',
    'Tułowice',
    'Głogówek',
    'Prudnik',
    'Strzelce Opolskie',
    'Opole',
    'Ustrzyki Dolne',
    'Brzozów',
    'Dębica',
    'Pilzno',
    'Jarosław',
    'Radymno',
    'Jasło',
    'Trzcinica',
    'Kołaczyce',
    'Nowy Żmigród',
    'Kolbuszowa',
    'Dukla',
    'Iwonicz',
    'Jedlicze',
    'Miejsce Piastowe',
    'Rymanów-Zdrój',
    'Rymanów',
    'Leżajsk',
    'Nowa Sarzyna',
    'Lubaczów',
    'Oleszyce',
    'Łańcut',
    'Żołynia',
    'Mielec',
    'Przecław',
    'Radomyśl Wielki',
    'Jeżowe',
    'Nisko',
    'Rudnik nad Sanem',
    'Dubiecko',
    'Przeworsk',
    'Kańczuga',
    'Zarzecze',
    'Ropczyce',
    'Sędziszów Małopolski',
    'Błażowa',
    'Boguchwała',
    'Głogów Małopolski',
    'Sokołów Małopolski',
    'Tyczyn',
    'Sanok',
    'Stalowa Wola',
    'Zaklików',
    'Czudec',
    'Strzyżów',
    'Grębów',
    'Nowa Dęba',
    'Lesko',
    'Krosno',
    'Przemyśl',
    'Rzeszów',
    'Tarnobrzeg',
    'Augustów',
    'Czarna Białostocka',
    'Łapy',
    'Michałowo',
    'Bielsk Podlaski',
    'Brańsk',
    'Grajewo',
    'Niećkowo',
    'Szczuczyn',
    'Hajnówka',
    'Kolno',
    'Jedwabne',
    'Knyszyn',
    'Mońki',
    'Sejny',
    'Puńsk',
    'Siemiatycze',
    'Ostrożany',
    'Drohiczyn',
    'Czartajew',
    'Sokółka',
    'Suchowola',
    'Wysokie Mazowieckie',
    'Czyżew',
    'Krzyżewo',
    'Zambrów',
    'Białystok',
    'Łomża',
    'Suwałki',
    'Bytów',
    'Miastko',
    'Chojnice',
    'Brusy',
    'Malachin',
    'Czersk',
    'Człuchów',
    'Czarne',
    'Pruszcz Gdański',
    'Kartuzy',
    'Przodkowo',
    'Sierakowice',
    'Somonino',
    'Żukowo',
    'Kościerzyna',
    'Kwidzyn',
    'Prabuty',
    'Lębork',
    'Malbork',
    'Nowy Dwór Gdański',
    'Hel',
    'Puck',
    'Władysławowo',
    'Ustka',
    'Kobylnica',
    'Czarna Woda',
    'Skórcz',
    'Starogard Gdański',
    'Lubichowo',
    'Tczew',
    'Gniew',
    'Pelplin',
    'Reda',
    'Rumia',
    'Wejherowo',
    'Dzierzgoń',
    'Sztum',
    'Gdańsk',
    'Gdynia',
    'Słupsk',
    'Sopot',
    'Będzin',
    'Czeladź',
    'Wojkowice',
    'Sławków',
    'Szczyrk',
    'Buczkowice',
    'Czechowice-Dziedzice',
    'Kozy',
    'Cieszyn',
    'Wisła',
    'Mnich',
    'Istebna',
    'Skoczów',
    'Złoty Potok',
    'Kamienica Polska',
    'Koniecpol',
    'Knurów',
    'Pyskowice',
    'Kłobuck',
    'Krzepice',
    'Lubliniec',
    'Psary',
    'Łaziska Górne',
    'Mikołów',
    'Ornontowice',
    'Myszków',
    'Koziegłowy',
    'Żarki',
    'Wola',
    'Gilowice',
    'Pawłowice',
    'Pszczyna',
    'Racibórz',
    'Czerwionka-Leszczyny',
    'Kalety',
    'Radzionków',
    'Tarnowskie Góry',
    'Kamieniec',
    'Bieruń',
    'Lędziny',
    'Rydułtowy',
    'Wodzisław Śląski',
    'Gogołowa',
    'Poręba',
    'Zawiercie',
    'Pilica',
    'Szczekociny',
    'Żywiec',
    'Łodygowice',
    'Milówka',
    'Bielsko-Biała',
    'Bytom',
    'Chorzów',
    'Częstochowa',
    'Dąbrowa Górnicza',
    'Gliwice',
    'Jastrzębie-Zdrój',
    'Jaworzno',
    'Katowice',
    'Mysłowice',
    'Piekary Śląskie',
    'Ruda Śląska',
    'Rybnik',
    'Siemianowice Śląskie',
    'Sosnowiec',
    'Świętochłowice',
    'Tychy',
    'Zabrze',
    'Żory',
    'Busko-Zdrój',
    'Jędrzejów',
    'Małogoszcz',
    'Wodzisław',
    'Kazimierza Wielka',
    'Cudzynowice',
    'Odonów',
    'Skalbmierz',
    'Bodzentyn',
    'Chęciny',
    'Chmielnik',
    'Łopuszno',
    'Nowa Słupia',
    'Nowiny',
    'Końskie',
    'Radoszyce',
    'Stąporków',
    'Opatów',
    'Ożarów',
    'Ostrowiec Świętokrzyski',
    'Pińczów',
    'Sandomierz',
    'Klimontów',
    'Chobrzany',
    'Zawichost',
    'Skarżysko-Kamienna',
    'Suchedniów',
    'Starachowice',
    'Osiek',
    'Połaniec',
    'Staszów',
    'Włoszczowa',
    'Kielce',
    'Bartoszyce',
    'Górowo Iławeckie',
    'Braniewo',
    'Działdowo',
    'Iłowo-Osada',
    'Lidzbark',
    'Rybno',
    'Pasłęk',
    'Ełk',
    'Giżycko',
    'Wydminy',
    'Iława',
    'Lubawa',
    'Fijewo',
    'Susz',
    'Kętrzyn',
    'Reszel',
    'Lidzbark Warmiński',
    'Orneta',
    'Mrągowo',
    'Mikołajki',
    'Nidzica',
    'Nowe Miasto Lubawskie',
    'Olecko',
    'Biskupiec',
    'Dobre Miasto',
    'Jeziorany',
    'Olsztynek',
    'Ostróda',
    'Morąg',
    'Biała Piska',
    'Pisz',
    'Ruciane-Nida',
    'Szczytno',
    'Rozogi',
    'Gołdap',
    'Węgorzewo',
    'Elbląg',
    'Olsztyn',
    'Chodzież',
    'Rataje',
    'Czarnków',
    'Krzyż Wielkopolski',
    'Lubasz',
    'Trzcianka',
    'Wieleń',
    'Gniezno',
    'Witkowo',
    'Gostyń',
    'Krobia',
    'Pogorzela',
    'Grodzisk Wielkopolski',
    'Jarocin',
    'Tarce',
    'Kotlin',
    'Lisków',
    'Opatówek',
    'Kępno',
    'Koło',
    'Kłodawa',
    'Kościelec',
    'Kleczew',
    'Skulsk',
    'Sompolno',
    'Kościan',
    'Krzywiń',
    'Nietążkowo',
    'Koźmin Wielkopolski',
    'Krotoszyn',
    'Rydzyna',
    'Włoszakowice',
    'Międzychód',
    'Nowy Tomyśl',
    'Opalenica',
    'Zbąszyń',
    'Oborniki',
    'Rogoźno',
    'Ostrów Wielkopolski',
    'Odolanów',
    'Przygodzice',
    'Ostrzeszów',
    'Piła',
    'Łobżenica',
    'Stara Łubianka',
    'Wyrzysk',
    'Dobrzyca',
    'Gizałki',
    'Pleszew',
    'Puszczykowo',
    'Buk',
    'Bolechowo',
    'Owińska',
    'Kórnik',
    'Mosina',
    'Pobiedziska',
    'Swarzędz',
    'Tarnowo Podgórne',
    'Bojanowo',
    'Jutrosin',
    'Miejska Górka',
    'Rawicz',
    'Słupca',
    'Strzałkowo',
    'Zagórów',
    'Pniewy',
    'Szamotuły',
    'Wronki',
    'Środa Wielkopolska',
    'Śrem',
    'Turek',
    'Wągrowiec',
    'Damasławek',
    'Gołańcz',
    'Glinno',
    'Przemęt',
    'Wolsztyn',
    'Miłosław',
    'Września',
    'Złotów',
    'Jastrowie',
    'Kalisz',
    'Konin',
    'Leszno',
    'Poznań',
    'Białogard',
    'Karlino',
    'Tychowo',
    'Choszczno',
    'Czaplinek',
    'Drawsko Pomorskie',
    'Kalisz Pomorski',
    'Złocieniec',
    'Goleniów',
    'Nowogard',
    'Gryfice',
    'Trzebiatów',
    'Chojna',
    'Gryfino',
    'Dziwnów',
    'Kamień Pomorski',
    'Wolin',
    'Kołobrzeg',
    'Gościno',
    'Polanów',
    'Barlinek',
    'Dębno',
    'Myślibórz',
    'Police',
    'Lipiany',
    'Pyrzyce',
    'Darłowo',
    'Sławno',
    'Stargard',
    'Szczecinek',
    'Barwice',
    'Biały Bór',
    'Świdwin',
    'Połczyn-Zdrój',
    'Wałcz',
    'Łobez',
    'Resko',
    'Koszalin',
    'Szczecin',
    'Świnoujście',
    'Pieszyce',
    'Kudowa-Zdrój',
    'Polanica-Zdrój',
    'Bożków',
    'Biedrzychowice',
    'Rudna',
    'Bierutów',
    'Międzybórz',
    'Chocianów',
    'Mokrzeszów',
    'Żmigród',
    'Krzyżowice',
    'Dobrzyń nad Wisłą',
    'Sypniewo',
    'Leśna Podlaska',
    'Różaniec',
    'Okszów',
    'Siennica Różana',
    'Kamionka',
    'Piotrowice',
    'Łęczna',
    'Kluczkowice',
    'Kamień Mały',
    'Bobowicko',
    'Ośno Lubuskie',
    'Wały B',
    'Czarnocin',
    'Szydłów',
    'Wolbórz',
    'Dobryszyce',
    'Złoczew',
    'Stare Bystre',
    'Brzeszcze',
    'Żabno',
    'Gołotczyzna',
    'Miętne',
    'Nowe Miasto nad Pilicą',
    'Stare Lubiejewo',
    'Karczew',
    'Golądkowo',
    'Zielona',
    'Komorno',
    'Bogdańczowice',
    'Brzostek',
    'Werynia',
    'Iwonicz-Zdrój',
    'Rakszawa',
    'Rzemień',
    'Nowosielce',
    'Rudka',
    'Wojewodzin',
    'Białowieża',
    'Goniądz',
    'Janów',
    'Lubkowo',
    'Owidz',
    'Swarożyn',
    'Barlewiczki',
    'Siewierz',
    'Międzyświeć',
    'Brynek',
    'Żarnowiec',
    'Węgierska Górka',
    'Krzelów',
    'Sędziszów',
    'Zagnańsk',
    'Chroberz',
    'Kisielice',
    'Kurzętnik',
    'Góra nad Notecią',
    'Trzemeszno',
    'Zduny',
    'Brzostowo',
    'Marszew',
    'Nowe Miasto nad Wartą',
    'Benice',
    'Smolnica',
    'Lubomierz',
    'Szczawno-Zdrój',
    'Jabłonowo Pomorskie',
    'Białe Błota',
    'Tarnogóra',
    'Dąbrowa',
    'Kajetany',
    'Mordy',
    'Ostrówek',
    'Branice',
    'Smętowo Graniczne',
    'Luzino',
    'Morawica',
    'Radawnica',
    'Osiek nad Wisłą',
    'Górsk',
    'Wyżnianka-Kolonia',
    'Rzgów',
    'Mikluszowice',
    'Trzciana',
    'Żegocina',
    'Szalowa',
    'Bibice',
    'Krynica-Zdrój',
    'Koszyce',
    'Gdów',
    'Halinów',
    'Lesznowola',
    'Józefosław',
    'Zalesie Górne',
    'Pęcice',
    'Stare Babice',
    'Kobyłka',
    'Pruchnik',
    'Sieniawa',
    'Kolbudy',
    'Trąbki Wielkie',
    'Barczewo',
    'Dywity',
    'Jankowice',
    'Uniejów',
    'Nowy Wiśnicz',
    'Supraśl',
    'Gronowo Górne',
    'Łbiska',
    'Brańszczyk',
    'Gołuchowice',
    'Gębice',
    'Piława Górna',
    'Wąsosz',
    'Długopole-Zdrój',
    'Szklary Górne',
    'Dobroszyce',
    'Kąty Wrocławskie',
    'Gądów',
    'Wojcieszów',
    'Wielgie',
    'Dorohusk',
    'Olbięcin',
    'Firlej',
    'Baczków',
    'Karczmiska Pierwsze',
    'Lipki Wielkie',
    'Stemplew',
    'Zagorzyce',
    'Zbylitowska Góra',
    'Kaczyna',
    'Jurki',
    'Zuzela',
    'Borkowice',
    'Stok Lacki-Folwark',
    'Leśnica',
    'Długobórz',
    'Barcice',
    'Damnica',
    'Ziemięcice',
    'Kruzy',
    'Miłakowo',
    'Szymanowo',
    'Łupki',
    'Rychwał',
    'Konarzew',
    'Suliszewo',
    'Niemieńsko',
    'Tanowo',
    'Ludów Polski',
    'Walim',
    'Sadowice',
    'Jerzmanice-Zdrój',
    'Kcynia',
    'Samostrzel',
    'Piotrków Kujawski',
    'Warlubie',
    'Śliwice',
    'Potoczek',
    'Milejów-Osada',
    'Widawa',
    'Piątek',
    'Prymusowa Wola',
    'Ksawerów',
    'Lututów',
    'Podborze',
    'Bystra',
    'Dobra',
    'Chełmiec',
    'Marcinkowice',
    'Wielogłowy',
    'Tęgoborze',
    'Lelis',
    'Laskowiec',
    'Wierzbica',
    'Teresin',
    'Długosiodło',
    'Studzieniec',
    'Kup',
    'Zawadzkie',
    'Frysztak',
    'Gorzyce',
    'Wasilków',
    'Ciechanowiec',
    'Debrzno',
    'Łęgowo',
    'Stara Kiszewa',
    'Skarszewy',
    'Ustroń',
    'Herby',
    'Łąka',
    'Rudy',
    'Krupski Młyn',
    'Tworóg',
    'Radlin',
    'Łagów',
    'Barycz',
    'Jóźwików',
    'Kamionek Wielki',
    'Piątki',
    'Dobrocin',
    'Orzysz',
    'Brzezie',
    'Kobylin',
    'Brenno',
    'Chraplewo',
    'Murowana Goślina',
    'Trzciniec',
    'Mieszkowice',
    'Bobolice',
    'Bonin',
    'Renice',
    'Brzeźnik',
    'Żeliszów',
    'Kruszyn',
    'Trzebień',
    'Bożejowice',
    'Kraśnik Dolny',
    'Ocice',
    'Osiecznica',
    'Świętoszów',
    'Kotla',
    'Czernina',
    'Ślubów',
    'Niechlów',
    'Siciny',
    'Jeżów Sudecki',
    'Miłków',
    'Pisarzowice',
    'Chełmsko Śląskie',
    'Marciszów',
    'Lewin Kłodzki',
    'Ludwikowice Kłodzkie',
    'Ścinawka Średnia',
    'Chocieszów',
    'Rokitki',
    'Legnickie Pole',
    'Pobiedna',
    'Radogoszcz',
    'Rakowice Wielkie',
    'Wleń',
    'Krośnice',
    'Miłowice',
    'Dziadowa Kłoda',
    'Radwanice',
    'Borów',
    'Przeworno',
    'Jaroszów',
    'Stanowice',
    'Szewce',
    'Zawonia',
    'Boguszów-Gorce',
    'Czarny Bór',
    'Sokołowsko',
    'Lubiąż',
    'Czernica',
    'Dobrzykowice',
    'Mirków',
    'Smolec',
    'Bielany Wrocławskie',
    'Pustków Żurawski',
    'Tyniec Mały',
    'Bardo',
    'Ciepłowody',
    'Kamieniec Ząbkowicki',
    'Stolec',
    'Świerzawa',
    'Koneck',
    'Zakrzewo',
    'Pokrzydowo',
    'Zbiczno',
    'Dąbrowa Chełmińska',
    'Borówno',
    'Lisewo',
    'Grubno',
    'Nowogród',
    'Radomin',
    'Radzyń Chełmiński',
    'Rojewo',
    'Tuczno',
    'Chrostkowo',
    'Ślesin',
    'Potulice',
    'Morzyce',
    'Kamień Krajeński',
    'Drzycim',
    'Brzozówka',
    'Książki',
    'Boniewo',
    'Kąkowa Wola',
    'Lubień Kujawski',
    'Lubraniec-Parcele',
    'Terespol',
    'Janów Podlaski',
    'Łomazy',
    'Chotyłów',
    'Sławatycze',
    'Biszcza',
    'Frampol',
    'Goraj',
    'Tereszpol-Zaorenda',
    'Sawin',
    'Dzwola',
    'Kocudza Pierwsza',
    'Stojeszyn Pierwszy',
    'Wierzchowiska Drugie',
    'Gościeradów-Folwark',
    'Księżomierz-Kolonia',
    'Szastarka',
    'Zakrzówek',
    'Abramów',
    'Skrobów-Kolonia',
    'Piotrków Pierwszy',
    'Krzczonów',
    'Dys',
    'Niemce',
    'Cyców',
    'Stoczek Łukowski',
    'Adamów',
    'Fiukówka',
    'Krzywda',
    'Okrzeja',
    'Radoryż Smolany',
    'Gołąbki',
    'Serokomla',
    'Jedlanka',
    'Jabłoń',
    'Stary Pożóg',
    'Wąwolnica',
    'Zabiele',
    'Wohyń',
    'Bobrowniki',
    'Ownia',
    'Leopoldów',
    'Moszczanka',
    'Michalów',
    'Tarnawatka',
    'Ulhówek',
    'Hańsk Pierwszy',
    'Urszulin',
    'Wola Uhruska',
    'Kalinowice',
    'Nowiny Wielkie',
    'Brójce',
    'Kolsko',
    'Konotop',
    'Przyborów',
    'Nowe Miasteczko',
    'Rzepin',
    'Kołczyn',
    'Bojadła',
    'Kargowa',
    'Bogaczów',
    'Trzebiechów',
    'Łęknica',
    'Brody',
    'Jasień',
    'Lipinki Łużyckie',
    'Szlichtyngowa',
    'Kluki',
    'Rusiec',
    'Dąbrowice',
    'Sędziejowice',
    'Sędziejowice-Kolonia',
    'Marzenin',
    'Kwiatkowice',
    'Jamno',
    'Nieborów',
    'Bedoń-Wieś',
    'Konstantynów Łódzki',
    'Lutomiersk',
    'Rząśnia',
    'Gomunice',
    'Kamieńsk',
    'Trębaczew',
    'Sadkowice',
    'Błaszki',
    'Barczew',
    'Bronisławów',
    'Burzenin',
    'Jarocice',
    'Klonowa',
    'Głuchów',
    'Czerniewice',
    'Lubochnia',
    'Komorniki',
    'Pątnów',
    'Kraszkowice',
    'Mierzyce',
    'Wierzchlas',
    'Łubnice',
    'Wójcin',
    'Sokolniki',
    'Popów Głowieński',
    'Lubianków',
    'Mąkolice',
    'Grotniki',
    'Jeżów',
    'Gawłów',
    'Łapczyca',
    'Proszówki',
    'Mętków',
    'Gromiec',
    'Młoszowa',
    'Czyżówka',
    'Żelazówka',
    'Radgoszcz',
    'Słupiec',
    'Skrzynka',
    'Korczyna',
    'Libusza',
    'Rożnowice',
    'Strzeszyn',
    'Kwiatonowice',
    'Mszanka',
    'Wola Łużańska',
    'Staszkówka',
    'Wysowa-Zdrój',
    'Gładyszów',
    'Przeginia Duchowna',
    'Wola Filipowska',
    'Kopanka',
    'Krzęcin',
    'Wola Kalinowska',
    'Wielmoża',
    'Modlnica',
    'Balice',
    'Ujanowice',
    'Kasina Wielka',
    'Kasinka Mała',
    'Raba Niżna',
    'Olszówka',
    'Łostówka',
    'Mszana Górna',
    'Podobin',
    'Słopnice',
    'Borzęta',
    'Bysina',
    'Droginia',
    'Jasienica',
    'Siepraw',
    'Harbutowice',
    'Krzywaczka',
    'Rudnik',
    'Kobielnik',
    'Wiśniowa',
    'Niskowa',
    'Krużlowa Wyżna',
    'Tylicz',
    'Muszynka',
    'Mochnaczka Wyżna',
    'Czarny Potok',
    'Kadcza',
    'Powroźnik',
    'Złockie',
    'Piwniczna-Zdrój',
    'Kluszkowce',
    'Kacwin',
    'Tylmanowa',
    'Bydlin',
    'Chechło',
    'Ryczówek',
    'Gołaczewy',
    'Przecieszyn',
    'Jawiszowice',
    'Bobrek',
    'Chełmek',
    'Gorzów',
    'Łęki',
    'Witkowice',
    'Bulowice',
    'Harmęże',
    'Polanka Wielka',
    'Podolsze',
    'Grodzisko',
    'Nowe Brzesko',
    'Palcza',
    'Krzeszów',
    'Lachowice',
    'Stryszawa',
    'Zembrzyce',
    'Radłów',
    'Zabawa',
    'Biskupice Radłowskie',
    'Zdrochec',
    'Niwka',
    'Zalasowa',
    'Koszyce Wielkie',
    'Wietrzychowice',
    'Gwoździec',
    'Nieciecza',
    'Ilkowice',
    'Inwałd',
    'Rzyki',
    'Targanice',
    'Zagórnik',
    'Brzeźnica',
    'Łączany',
    'Zarzyce Wielkie',
    'Izdebnik',
    'Ryczów',
    'Bachowice',
    'Spytkowice',
    'Tomice',
    'Witanowice',
    'Radocza',
    'Wieprz',
    'Przybradz',
    'Frydrychowice',
    'Przybyszew',
    'Gołymin-Ośrodek',
    'Grudusk',
    'Borowie',
    'Głosków',
    'Izdebno',
    'Szczawin Kościelny',
    'Jaktorów',
    'Chynów',
    'Brzostowiec',
    'Warka',
    'Gniewoszów',
    'Grabów nad Pilicą',
    'Jabłonna',
    'Krępa Kościelna',
    'Lipsko',
    'Rzeczniów',
    'Huszlew',
    'Platerów',
    'Serpelice',
    'Karniewo',
    'Młynarze',
    'Cegłów',
    'Cisie',
    'Okuniew',
    'Stanisławów',
    'Szreńsk',
    'Kazuń Nowy',
    'Zakroczym',
    'Dylewo',
    'Wąsewo',
    'Sobiekursk',
    'Otwock Wielki',
    'Sobienie-Jeziory',
    'Kąty',
    'Pęchery',
    'Prażmów',
    'Chodkowo-Działki',
    'Nowe Miszewo',
    'Rogozino',
    'Nowa Wieś',
    'Jednorożec',
    'Rzuców',
    'Gielniów',
    'Winnica',
    'Zatory',
    'Gózd',
    'Chwałowice',
    'Wsola',
    'Jedlińsk',
    'Skaryszew',
    'Korczew',
    'Kotuń',
    'Mokobody',
    'Niwiski',
    'Hołubla',
    'Przesmyki',
    'Białki',
    'Chodów',
    'Stok Lacki',
    'Nowe Iganie',
    'Skórzec',
    'Suchożebry',
    'Wiśniew',
    'Seroczyn',
    'Wodynie',
    'Borki-Wyrki',
    'Zawidz Kościelny',
    'Bielany-Jarosławy',
    'Rozbity Kamień',
    'Ceranów',
    'Kosów Lacki',
    'Sabnie',
    'Skibniew-Podawce',
    'Sterdyń',
    'Kampinos',
    'Grębków',
    'Topór',
    'Nowe Ręczaje',
    'Ciemne',
    'Mokra Wieś',
    'Miąse',
    'Kozły',
    'Postoliska',
    'Duczki',
    'Leśniakowizna',
    'Stare Bosewo',
    'Adelin',
    'Zabrodzie',
    'Policzna',
    'Czarnolas',
    'Tczów',
    'Lubowidz',
    'Siemiątkowo',
    'Bartniki',
    'Skarbimierz-Osiedle',
    'Mąkoszyce',
    'Przylesie',
    'Baborów',
    'Gościęcin',
    'Wronin',
    'Długomiłowice',
    'Reńska Wieś',
    'Większyce',
    'Pokrzywnica',
    'Byczyna',
    'Lasowice Wielkie',
    'Kórnica',
    'Jastrzębie',
    'Smarchowice Wielkie',
    'Głuszyna',
    'Ligota Książęca',
    'Pokój',
    'Korfantów',
    'Przechód',
    'Ścinawa Mała',
    'Bielice',
    'Koperniki',
    'Biała Nyska',
    'Goświnowice',
    'Niwnica',
    'Grądy',
    'Dziewiętlice',
    'Trzeboszowice',
    'Goszowice',
    'Prusinowice',
    'Chróścina',
    'Skoroszyce',
    'Gosławice',
    'Dębska Kuźnia',
    'Ozimek',
    'Boguszyce',
    'Złotniki',
    'Raszowa',
    'Łącznik',
    'Biała',
    'Szybowice',
    'Zalesie Śląskie',
    'Kadłub',
    'Lutowiska',
    'Niebocko',
    'Orzechówka',
    'Żyraków',
    'Straszęcin',
    'Zamiechów',
    'Pawłosiów',
    'Brzyska',
    'Sieklówka',
    'Sowina',
    'Osiek Jasielski',
    'Umieszcz',
    'Kolbuszowa Dolna',
    'Dzikowiec',
    'Bóbrka',
    'Zręcin',
    'Milcza',
    'Posada Górna',
    'Brzóza Królewska',
    'Kowalówka',
    'Basznia Dolna',
    'Lisie Jamy',
    'Ruda Różaniecka',
    'Krzemienica',
    'Kosina',
    'Chorzelów',
    'Trześń',
    'Tuszyma',
    'Dulcza Wielka',
    'Tuszów Narodowy',
    'Jaślany',
    'Wadowice Górne',
    'Jata',
    'Bircza',
    'Przedmieście Dubieckie',
    'Orły',
    'Krówniki',
    'Łętownia',
    'Nehrybka',
    'Grochowce',
    'Żurawica',
    'Jagiełła',
    'Skrzyszów',
    'Góra Ropczycka',
    'Dynów',
    'Pogwizdów Nowy',
    'Wysoka Głogowska',
    'Krasne',
    'Malawa',
    'Strażów',
    'Górno',
    'Nienadówka',
    'Trzeboś',
    'Jasionka',
    'Wólka Podleśna',
    'Zaczernie',
    'Bojanów',
    'Radomyśl nad Sanem',
    'Lipa',
    'Turbia',
    'Zaleszany',
    'Pstrągowa',
    'Wyżne',
    'Lubla',
    'Konieczkowa',
    'Lutcza',
    'Dobrzechów',
    'Godowa',
    'Baranów Sandomierski',
    'Skopanie',
    'Wola Baranowska',
    'Średnia Wieś',
    'Uherce Mineralne',
    'Lipsk',
    'Dobrzyniewo Duże',
    'Fasty',
    'Nowe Aleksandrowo',
    'Juchnowiec Dolny',
    'Księżyno',
    'Ogrodniczki',
    'Suraż',
    'Turośń Kościelna',
    'Tykocin',
    'Zabłudów',
    'Rajgród',
    'Czeremcha',
    'Stawiski',
    'Piątnica Poduchowna',
    'Marianowo',
    'Śniadowo',
    'Jasionówka',
    'Grodzisk',
    'Mielnik',
    'Różanystok',
    'Dąbrowa Białostocka',
    'Krynki',
    'Szumowo',
    'Borzytuchom',
    'Brzeźno Szlacheckie',
    'Lipnica',
    'Tuchomie',
    'Rytel',
    'Łąg',
    'Rzeczenica',
    'Bielkówko',
    'Lublewo Gdańskie',
    'Borkowo',
    'Brodnica Górna',
    'Dzierżążno',
    'Kamienica Szlachecka',
    'Klukowa Huta',
    'Stężyca',
    'Szymbark',
    'Mściszewice',
    'Dziemiany',
    'Łubiana',
    'Wielki Klincz',
    'Nowy Klincz',
    'Skorzewo',
    'Wąglikowice',
    'Garczyn',
    'Liniewo',
    'Grabowo Kościerskie',
    'Siemirowice',
    'Cewice',
    'Łebień',
    'Miłoradz',
    'Marzęcino',
    'Kmiecin',
    'Drewnica',
    'Dębogórze',
    'Mosty',
    'Kłanino',
    'Połchowo',
    'Żelistrzewo',
    'Dębnica Kaszubska',
    'Gogolewo',
    'Motarzyno',
    'Główczyce',
    'Kępice',
    'Przytocko',
    'Siemianice',
    'Smołdzino',
    'Kaliska',
    'Osieczna',
    'Szlachta',
    'Rywałd',
    'Pinczyn',
    'Opalenie',
    'Rajkowy',
    'Rudno',
    'Mała Słońca',
    'Subkowy',
    'Turze',
    'Choczewo',
    'Gniewino',
    'Kostkowo',
    'Rozłazino',
    'Strzebielino',
    'Łęczyce',
    'Stary Targ',
    'Czernin',
    'Sączów',
    'Dobieszowice',
    'Sarnów',
    'Wojkowice Kościelne',
    'Żelisławice',
    'Bestwinka',
    'Bestwina',
    'Janowice',
    'Godziszka',
    'Wieszczęta',
    'Rudzica',
    'Meszna',
    'Zaborze',
    'Bażanowice',
    'Kiczyce',
    'Pogórze',
    'Bąków',
    'Zabłocie',
    'Drogomyśl',
    'Pruchna',
    'Rększowice',
    'Aleksandria',
    'Kopalnia',
    'Lgota Mała',
    'Lelów',
    'Słowik',
    'Przyrów',
    'Rudniki',
    'Chudów',
    'Przyszowice',
    'Paniówki',
    'Pilchowice',
    'Stanica',
    'Wilcza',
    'Żernica',
    'Pławniowice',
    'Poniszowice',
    'Rudziniec',
    'Wielowieś',
    'Kamyk',
    'Łobodno',
    'Parzymiechy',
    'Lipie',
    'Rębielice Królewskie',
    'Zawady',
    'Popów',
    'Więcki',
    'Kalej',
    'Boronów',
    'Lisów',
    'Kochcice',
    'Kochanowice',
    'Lisowice',
    'Miedźna',
    'Golasowice',
    'Piasek',
    'Studzienice',
    'Czarków',
    'Wisła Wielka',
    'Kryry',
    'Mizerów',
    'Radostowice',
    'Rudziczka',
    'Rzuchów',
    'Kobyla',
    'Pogrzebień',
    'Wojnowice',
    'Owsiszcze',
    'Górki Śląskie',
    'Babice',
    'Zawada Książęca',
    'Samborowice',
    'Krowiarki',
    'Szczerbice',
    'Jejkowice',
    'Lyski',
    'Adamowice',
    'Pstrążna',
    'Miasteczko Śląskie',
    'Potępa',
    'Orzech',
    'Nakło Śląskie',
    'Wojska',
    'Boruszowice',
    'Miedary',
    'Pszów',
    'Łaziska',
    'Godów',
    'Skrbeńsko',
    'Gorzyczki',
    'Połomia',
    'Ogrodzieniec',
    'Wierbka',
    'Goleniowy',
    'Krzyżowa',
    'Pewel Wielka',
    'Jeleśnia',
    'Korbielów',
    'Koszarawa',
    'Słotwina',
    'Leśna',
    'Twardorzeczka',
    'Kamesznica',
    'Pewel Ślemieńska',
    'Zborów',
    'Solec-Zdrój',
    'Stopnica',
    'Niziny',
    'Wiślica',
    'Wzdół Rządowy',
    'Piotrkowice',
    'Daleszyce',
    'Cedzyna',
    'Kostomłoty Drugie',
    'Rudki',
    'Micigózd',
    'Raków',
    'Kowala',
    'Bolechowice',
    'Samsonów',
    'Tumlin-Węgle',
    'Nowy Kazanów',
    'Modliszewice',
    'Pomyków',
    'Lasocin',
    'Sarnówek Duży',
    'Szewna',
    'Kije',
    'Sędowice',
    'Węchadłów',
    'Kozubów',
    'Bogucice Pierwsze',
    'Świniary Stare',
    'Łączna',
    'Styków',
    'Lubienia',
    'Ruda',
    'Wąchock',
    'Ruszcza',
    'Strzegomek',
    'Rytwiany',
    'Kurozwęki',
    'Koniemłoty',
    'Dobromierz',
    'Kluczewsko',
    'Skorków',
    'Krasocin',
    'Oleszno',
    'Chlewice',
    'Konieczno',
    'Kurzelów',
    'Bezledy',
    'Sępopol',
    'Frombork',
    'Pieniężno',
    'Narzym',
    'Gronowo Elbląskie',
    'Jegłownik',
    'Tolkmicko',
    'Nowa Wieś Ełcka',
    'Straduny',
    'Stare Juchy',
    'Miłki',
    'Ryn',
    'Zalewo',
    'Lubomino',
    'Bratian',
    'Wieliczki',
    'Łęgajny',
    'Gietrzwałd',
    'Sząbruk',
    'Purda',
    'Klebark Wielki',
    'Stawiguda',
    'Świątki',
    'Łukta',
    'Samborowo',
    'Dąbrówka',
    'Jedwabno',
    'Szczytniki Duchowne',
    'Jankowo Dolne',
    'Kłecko',
    'Mielżyn',
    'Borek Wielkopolski',
    'Zimnowoda',
    'Granowo',
    'Rostarzewo',
    'Ruchocice',
    'Rusko',
    'Mieszków',
    'Potarzyca',
    'Łuszczanów',
    'Siedlemin',
    'Wilkowyja',
    'Janków Drugi',
    'Piotrów',
    'Godziesze Wielkie',
    'Wola Droszewska',
    'Iwanowice',
    'Marchwacz-Kolonia',
    'Radliczyce',
    'Szczytniki',
    'Russów',
    'Dębe',
    'Żelazków',
    'Słupia pod Kępnem',
    'Łęka Opatowska',
    'Grzegorzew',
    'Dobrosołowo',
    'Budzisław Kościelny',
    'Mąkolno',
    'Racot',
    'Jerka',
    'Bieżyń',
    'Czacz',
    'Stare Bojanowo',
    'Garzyn',
    'Kąkolewo',
    'Świerczyna',
    'Chrzypsko Wielkie',
    'Kamionna',
    'Łowyń',
    'Sieraków',
    'Wąsowo',
    'Zębowo',
    'Bukowiec',
    'Chrośnica',
    'Nądnia',
    'Przyprostynia',
    'Chrustowo',
    'Kowanówko',
    'Kotowiecko',
    'Wtórek',
    'Topola Mała',
    'Wysocko Wielkie',
    'Dębnica',
    'Granowiec',
    'Sośnie',
    'Szydłowo',
    'Broniszewice',
    'Czermin',
    'Kuchary',
    'Kucharki',
    'Gołuchów',
    'Kowalew',
    'Niepruszewo',
    'Dopiewo',
    'Kleszczewo',
    'Tulce',
    'Napachanie',
    'Rokietnica',
    'Jeziorki',
    'Modrze',
    'Chludowo',
    'Biedrusko',
    'Dłoń',
    'Słowikowo',
    'Cienin Kościelny',
    'Młodojewo',
    'Ostroróg',
    'Murzynowo Leśne',
    'Pięczkowo',
    'Chocicza',
    'Klęka',
    'Przykona',
    'Słodków',
    'Kaczki Średnie',
    'Łekno',
    'Kluczewo',
    'Kaszczor',
    'Radomierz',
    'Kopanica',
    'Kębłowo',
    'Obra',
    'Świętno',
    'Powodowo',
    'Nekla',
    'Targowa Górka',
    'Zasutowo',
    'Lotyń',
    'Tarnówka',
    'Stara Wiśniewka',
    'Bierzwnik',
    'Bobrowo',
    'Białuń',
    'Stepnica',
    'Płoty',
    'Pobierowo',
    'Rewal',
    'Cedynia',
    'Moryń',
    'Kołbacz',
    'Golczewo',
    'Chociwel',
    'Dobrzany',
    'Ińsko',
    'Grzmiąca',
  ],
  foreign_languages: [
    'Angielski',
    'Niemiecki',
    'Hiszpański',
    'Francuski',
    'Rosyjski',
    'Włoski',
    'Chiński',
    'Japoński',
    'Portugalski',
    'Arabski',
    'Koreański',
    'Turecki',
  ],
  extended_subjects: [
    'Biologia',
    'Chemia',
    'Matematyka',
    'Informatyka',
    'WOS',
    'Polski',
    'Historia',
  ],
  profession: [
    'Lekarz',
    'Programista',
    'Automatyk',
    'Prawnik',
    'Nauczyciel',
    'Kierownik',
    'Menadżer',
  ],
  profiles: ['Biol-Chem', 'Mat-Inf', 'Ekonomiczny', 'Prawo'],
};

export const regionsConverted = {
  'WOJ. DOLNOŚLĄSKIE': 'Dolnośląskie',
  'WOJ. KUJAWSKO-POMORSKIE': 'Kujawsko-Pomorskie',
  'WOJ. LUBELSKIE': 'Lubelskie',
  'WOJ. LUBUSKIE': 'Lubuskie',
  'WOJ. ŁÓDZKIE': 'Łódzkie',
  'WOJ. MAŁOPOLSKIE': 'Małopolskie',
  'WOJ. MAZOWIECKIE': 'Mazowieckie',
  'WOJ. OPOLSKIE': 'Opolskie',
  'WOJ. PODKARPACKIE': 'Podkarpackie',
  'WOJ. PODLASKIE': 'Podlaskie',
  'WOJ. POMORSKIE': 'Pomorskie',
  'WOJ. ŚLĄSKIE': 'Śląskie',
  'WOJ. ŚWIĘTOKRZYSKIE': 'Świętokrzyskie',
  'WOJ. WARMIŃSKO-MAZURSKIE': 'Warmińsko-Mazurskie',
  'WOJ. WIELKOPOLSKIE': 'Wielkopolskie',
  'WOJ. ZACHODNIOPOMORSKIE': 'Zachodniopomorskie',
};
